services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $templateDir: "%kernel.project_dir%/templates"
            $modulesDir: "%kernel.project_dir%/modules"

    _instanceof:
        Symfony\Component\Console\Command\Command:
            tags: ["console.command"]
        Youness\PrestashopMaker\Generator\GeneratorInterface:
            tags: ["app.generator"]

    Youness\PrestashopMaker\:
        resource: "%kernel.project_dir%/src/*"
        exclude: "%kernel.project_dir%/src/{Entity,Tests,Kernel.php}"
